
[tool.black]
line-length = 100
target-version = ['py310']
skip-string-normalization = true

[tool.isort]
profile = "black"

[tool.flake8]
exclude = []
ignore = []
max-line-length = 100
max-complexity = 18
select = []
