name: cu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - jupyterlab
  - pandas
  - proplot
  - plotnine
  - seaborn
  - hvplot
  - black
  - flake8
  - isort
  - pre-commit
